name: flutter_starter_kit
description: A dart command line tool to create a flutter app with different pre-defined modules available for quick feature development
version: 1.0.0
repository: https://github.com/Konstanius/flutter_starter_kit

environment:
  sdk: ^3.1.1

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
